# Site settings
title: 
header-img: img/home-bg.png
email: eakelly220@gmail.com
copyright_name: Ekelly140
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Ekelly140
learn_profile: Ekelly140
email_username: eakelly220@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
